name: side_run
description: "Tap-to-jump endless runner."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.5.0
  flame_audio: ^2.11.10
  cupertino_icons: ^1.0.8
  simple_parallax: ^0.1.0
  google_mobile_ads: ^6.0.0
  audioplayers: ^6.5.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true  
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/skyline/back.png
    - assets/images/skyline/buildings.png
    - assets/images/skyline/front.png
    - assets/images/          
    - assets/audio/tap.wav
    - assets/audio/jump.wav
    - assets/audio/gg.mp3
    - assets/audio/soundtrack.mp3
    - assets/audio/aura.mp3

    - assets/images/platform/pl.png
    - assets/images/platform/pc.png
    - assets/images/platform/pr.png
    - assets/images/platform/pm.png
